### ISSUE TITLE
Allow returning a Promise?

### ISSUE THREAD

**Issue by ianwremmel** [facebook/jscodeshift#210]
I'm trying to write a codemod that opens tickets for each TODO or FIXME in my code and updates the in-code comments to include the link to the ticket. As far as I can tell, that's currently impossible given jscodemod's API is synchronous.

Is there a way to do this now? If not, would you be open to a PR that allows the transform function to return a Promise?

**Comment by ngryman** [comment]
👆It seems that this issue has been resolved and should be closed.

**Comment by fkling** [comment]
@ngryman: It's not resolved, that commit points to a different repo.

**Comment by mstruensee** [comment]
will this be a new feature? or not a desired feature to have?

**Comment by Daniel15** [comment]
This is now available in 0.12.0.
